# Generated by Django 5.1.7 on 2025-03-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clerkuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='clerkuser',
            name='clerk_id',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False, unique=True),
        ),
    ]
