# Generated by Django 5.1.7 on 2025-05-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz_status_alter_option_id_alter_question_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='highest_score',
            field=models.IntegerField(default=0),
        ),
    ]
