# Generated by Django 5.1.7 on 2025-03-21 12:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('69790285-8323-4988-9df5-62fa266800ac'), primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
