# Generated by Django 5.1.7 on 2025-06-10 07:00

import django.db.models.deletion
import summary.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_remove_clerkuser_id_alter_clerkuser_clerk_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField(null=True)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('processed', 'processed'), ('error', 'error'), ('processing', 'processing')], default='processing', max_length=20)),
                ('cover', models.ImageField(null=True, upload_to=summary.models.cover_path)),
                ('error_message', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('favorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='user.clerkuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
