# Generated by Django 5.1.7 on 2025-03-21 12:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
        ('user', '0002_remove_clerkuser_id_alter_clerkuser_clerk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='content',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='title',
            field=models.CharField(default='hi', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='user.clerkuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='summary',
            name='id',
            field=models.UUIDField(default=uuid.UUID('30d68fff-6f34-4f77-bfd7-01c2dd13a5ae'), primary_key=True, serialize=False, unique=True),
        ),
    ]
