# Generated by Django 5.1.7 on 2025-06-12 07:13

import summary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='file',
            field=models.FileField(null=True, upload_to=summary.models.file_path),
        ),
        migrations.AlterField(
            model_name='summary',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
