# Generated by Django 5.1.7 on 2025-03-22 04:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0002_summary_content_summary_title_summary_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='summary',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e9ece578-e9ec-4b8c-b124-58018c27531e'), primary_key=True, serialize=False, unique=True),
        ),
    ]
