# Generated by Django 5.1.7 on 2025-03-22 04:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0003_summary_processed_alter_summary_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='processed',
        ),
        migrations.AddField(
            model_name='summary',
            name='status',
            field=models.CharField(choices=[('processed', 'processed'), ('error', 'error'), ('processing', 'processing')], default='processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='summary',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5fa8f2c0-cad8-4f65-acf0-f13beeee06a1'), primary_key=True, serialize=False, unique=True),
        ),
    ]
