# Generated by Django 5.1.7 on 2025-06-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0003_alter_summary_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
