# Generated by Django 5.1.7 on 2025-03-23 02:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0004_remove_summary_processed_summary_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
