# Generated by Django 5.1.7 on 2025-06-12 23:58

import summary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0004_alter_summary_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='file',
            field=models.FileField(max_length=2000, upload_to=summary.models.file_path),
        ),
    ]
