# Generated by Django 5.1.7 on 2025-06-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0005_alter_summary_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='content',
            field=models.JSONField(null=True),
        ),
    ]
