# Generated by Django 5.1.7 on 2025-04-05 23:57

import summary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0005_alter_summary_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='cover',
            field=models.ImageField(null=True, upload_to=summary.models.generate_path),
        ),
    ]
