# Generated by Django 5.1.7 on 2025-05-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0006_summary_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='error_message',
            field=models.TextField(null=True),
        ),
    ]
