# Generated by Django 5.1.7 on 2025-05-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0008_summary_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
