# Generated by Django 5.1.7 on 2025-05-14 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0009_alter_summary_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'ordering': ['-created_at']},
        ),
    ]
